
package chatbot;

import java.awt.Color;
import java.awt.Cursor;


public class Frame_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frame_1.class.getName());

    private Bot bot;
    private User user = new User("User");
    private boolean isDarkTheme = true;
    
    public Frame_1() {
        initComponents();
        this.bot = new Bot(user);
        textArea1.setCursor(Cursor.getDefaultCursor());
        textArea1.append("Bot: Hello! Type a message below and press Enter.\n\n");
         getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        textArea1 = new java.awt.TextArea();
        textField1 = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        ThemeChanger = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NunuBot");
        setBackground(java.awt.Color.gray);
        setForeground(new java.awt.Color(102, 102, 102));

        textArea1.setBackground(new java.awt.Color(153, 153, 153));
        textArea1.setEditable(false);
        textArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textArea1MouseClicked(evt);
            }
        });
        textArea1.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textArea1TextValueChanged(evt);
            }
        });

        textField1.setBackground(new java.awt.Color(153, 153, 153));
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu2.setText("File");

        ThemeChanger.setText("Theme");
        ThemeChanger.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ThemeChanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemeChangerActionPerformed(evt);
            }
        });
        jMenu2.add(ThemeChanger);

        jMenuItem2.setText("Exit");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textArea1TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textArea1TextValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_textArea1TextValueChanged

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
       
        String input = textField1.getText().trim();
    if (input.isEmpty()) return;

    // Show what the user typed
    textArea1.append("You: " + input + "\n");
    textField1.setText(""); // clear the input field

    // Handle exit
    if (input.equalsIgnoreCase("exit")) {
        textArea1.append("Bot: Goodbye, " + user.name + ". Shutting down...\n");
        textField1.setEnabled(false);
        
        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> System.exit(0));
        timer.setRepeats(false); 
        timer.start();
        
        return;
    }

    // Pass to bot logic
    user.lastInput = input;
    user.updateScore();

    String reply = bot.processMessage(input);
   
    if (reply.equals("COMMAND_CLEAR")) {
    textArea1.setText("Bot: Hello! Type a message below and press Enter. \n\n");
    } else {
    
    textArea1.append("Bot: " + reply + "\n");
    textArea1.append("(Score: " + user.conversationScore + ")\n\n");
}
    
        
    }//GEN-LAST:event_textField1ActionPerformed

    private void textArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textArea1MouseClicked
        
        
        
    }//GEN-LAST:event_textArea1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String helpMessage = bot.processMessage("Help");
        textArea1.append("System: " + helpMessage + "\n\n");
        textField1.requestFocus();
        
        
         // upon pressing button, update the text area to show the list of commands
   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String reply = bot.processMessage("Clear");
        
         if (reply.equals("COMMAND_CLEAR")) {
        
        textArea1.setText("Bot: Hello! Type a message below and press Enter.\n\n"); // resets text area
    }
    
    
    textField1.requestFocus();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        System.exit(0);

        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ThemeChangerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemeChangerActionPerformed
        
        if (isDarkTheme) {
        // Switch to Light Theme
        getContentPane().setBackground(Color.WHITE);
        textArea1.setBackground(Color.WHITE);
        textArea1.setForeground(Color.BLACK);
        textField1.setBackground(Color.WHITE);
        textField1.setForeground(Color.BLACK);
        
        isDarkTheme = false; // Update the state
    } else {
        // Switch back to Original Dark Theme
        getContentPane().setBackground(Color.DARK_GRAY);
        textArea1.setBackground(Color.DARK_GRAY);
        textArea1.setForeground(Color.WHITE); 
        textField1.setBackground(Color.DARK_GRAY);
        textField1.setForeground(Color.WHITE);
        
        isDarkTheme = true; // Update the state
    }
    }//GEN-LAST:event_ThemeChangerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> new Frame_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ThemeChanger;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
